version: "3.0"
services:
  seednode:
    image: seednode:dev
    container_name: seednode
    build:
      context: .
      dockerfile: docker/seednode/Dockerfile
    command: "--rest-api-interface=0.0.0.0:10000"
    networks:
      local-testnet:
        ipv4_address: 172.18.0.2
    volumes:
      - /home/cristu/MultiversX/testnet/seednode/config:/go/mx-chain-go/cmd/seednode/config

  validator00:
    image: node:dev
    container_name: validator00
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: ["--rest-api-interface=0.0.0.0:10200", "--sk-index=0", "--config=./config/config_validator.toml"]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.3
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [seednode]

  validator01:
    image: node:dev
    container_name: validator01
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: ["--rest-api-interface=0.0.0.0:10201", "--sk-index=1", "--config=./config/config_validator.toml"]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.4
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [seednode]

  validator02:
    image: node:dev
    container_name: validator02
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: ["--rest-api-interface=0.0.0.0:10202", "--sk-index=2", "--config=./config/config_validator.toml"]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.5
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [seednode]

  validator03:
    image: node:dev
    container_name: validator03
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10203", "--sk-index=3", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.6
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]

  validator04:
    image: node:dev
    container_name: validator04
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10204", "--sk-index=4", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.7
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]

  validator05:
    image: node:dev
    container_name: validator05
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10205", "--sk-index=5", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.8
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]


  validator06:
    image: node:dev
    container_name: validator06
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10206", "--sk-index=6", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.9
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]

  validator07:
    image: node:dev
    container_name: validator07
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10207", "--sk-index=7", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.10
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]

  validator08:
    image: node:dev
    container_name: validator08
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: [ "--rest-api-interface=0.0.0.0:10208", "--sk-index=8", "--config=./config/config_validator.toml" ]
    networks:
      local-testnet:
        ipv4_address: 172.18.0.11
    volumes:
      - /home/cristu/MultiversX/testnet/node/config:/go/mx-chain-go/cmd/node/config
    depends_on: [ seednode ]


  proxy:
    image:  multiversx/chain-proxy:v1.1.45-sp4
    container_name: chain-proxy
    ports:
      - "7950:7950"
    depends_on: [validator00, validator01, validator02]
    networks:
      local-testnet:
    volumes:
      - ./test-config/proxy/config:/mx-chain-proxy-go/cmd/proxy/config

networks:
  local-testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1