name: Build local testnet

on:
  pull_request:
    branches: [ master, rc/* ]
    types: [opened, ready_for_review]
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    name: Build
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Check out mx-deploy-go
        uses: actions/checkout@v4
        with:
          repository: multiversx/mx-chain-deploy-go
          path: mx-chain-deploy-go

      - name: Build node and seednode images
        run: |
          docker build -f docker/node/Dockerfile . -t node:dev
          docker build -f docker/seednode/Dockerfile . -t node:dev

      - name: Start localnet
        id: generate-config
        run: |
          cd ${GITHUB_WORKSPACE}/scripts/docker-testnet
          export TESTNETDIR=${GITHUB_WORKSPACE}/docker-testnet
          export CI_RUN=1
          ./start.sh
          echo "Check everything is alright. Remove once confirmed"
          docker ps
          curl http://localhost:7950
#
#      - name: Deploy local testnet
#        run: |
#          export TESTNETDIR=${GITHUB_WORKSPACE}/docker-testnet
#          echo ${TESTNETDIR}
#          docker compose up -d
#          docker ps -a
#          docker logs seednode
